pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["bare_de_menu.htm","Bare de Menu","Barerde Menu",""],
["bibliotheque_des_circuits_comb.htm","Bibliothèque des composants  &#62; Bibliothèque des circuits combinatoires","Bibliothèque des composants Bibliothèque des circuits combinatoires Navigation: Bibliothèque des composants Bibliothèque des circuits combinatoires ",""],
["bibliotheque_des_circuits_sequ.htm","Bibliothèque des composants  &#62; Bibliothèque des circuits séquentiels","Bibliothèque des composants Bibliothèque des circuits séquentiels Navigation: Bibliothèque des composants Bibliothèque des circuits séquentiels En...",""],
["bibliotheque_des_composants_.htm","Bibliothèque des composants ","Bibliothèque des composants Navigation: No topics above this level Bibliothèque des composants Lorem ipsum dolor sit amet,nconsectetuer adipiscing...",""],
["bibliotheque_des_composants_co.htm","Bibliothèque des composants combinatoires","Bibliothpque des composants comsinatoires",""],
["bibliotheque_des_composants_se.htm","Bibliothèque des composants séquentiels","Bibliothèque des composants séquentiels",""],
["bibliotheque_des_portes_logiqu.htm","Bibliothèque des composants de base ","Bibliothèque des composants de base ",""],
["bienvenue_sur_circlab_.htm","Bienvenue sur CircLab ","Bienvenue sur CircLab !",""],
["chapter_2.htm","Chapter 2","Chapter 2 Navigation: No topics above this level Chapter 2 E ter topic text here. ",""],
["compteurs__diviseurs_de_freque.htm","Bibliothèque des composants séquentiels &#62; Compteurs/ Diviseurs de fréquence ","Compteurs/ Diviseurs de fréquence ",""],
["decodeur_encodeur.htm","Bibliothèque des composants combinatoires &#62; Décodeur/Encodeur","Décodeur/Encodeur",""],
["etape0_se_familiariser_avec_ci.htm","Bienvenue sur CircLab  &#62; Etape0: Se familiariser avec CircLab","Etape0: Se familiariser avec CircLab",""],
["etape1_ajout_des_portes.htm","Bienvenue sur CircLab  &#62; Etape1: Ajout des portes","Etape1: Ajout des portes",""],
["etape2_ajout_des_liaisons.htm","Bienvenue sur CircLab  &#62; Etape2: Ajout des liaisons","Etape2: Ajout des liaisons",""],
["etape3_tester_le_circuit.htm","Bienvenue sur CircLab  &#62; Etape3: Tester le circuit","Etape3: Tester le circuit",""],
["horloge.htm","Bibliothèque des composants séquentiels &#62; Horloge","Horloge",""],
["introduction.htm","A propos","A propos",""],
["la_porte_et.htm","Bibliothèque des composants de base  &#62; La porte ET/ou/NonOU/NonET","La Torte ET/ou/NonOU/NonET",""],
["la_porte_non.htm","Bibliothèque des composants de base  &#62; La porte NON","La porte NON",""],
["la_porte_xor_xnor.htm","Bibliothèque des composants de base  &#62; La porte XOR/XNOR","La /orte XOR/XNOR",""],
["les_bascules.htm","Bibliothèque des composants séquentiels &#62; Les bascules (flipflop)","Les bascules (flipflop)",""],
["les_input_output.htm","Bibliothèque des composants de base  &#62; Les InPut/OutPut","Les InPut/OutPut",""],
["les_registres.htm","Bibliothèque des composants séquentiels &#62; Les registres","Les reggstres",""],
["menu_des_modifications.htm","Bare de Menu &#62; Menu des modifications","Menu des modifimations",""],
["menu_des_options.htm","Bare de Menu &#62; Menu des options","Menu des options",""],
["menu_des_proprietes_.htm","Bare de Menu &#62; Menu des propriétés ","Menu des propriétés ",""],
["multiplexeur_demultiplexeur.htm","Bibliothèque des composants combinatoires &#62; Multiplexeur/Demultiplexeur","Multiplexeur/Demultiplexeur",""],
["new_topic.htm","Chapter 2 &#62; Sub chapter 2.1 &#62; New topic","New topic Navigation: Chapter 2 Sub chapter 2.1 New topic Enter topic text here. ",""],
["overview.htm","Chapter 2 &#62; Overview","Overview Navigation: Chapter 2 Overview Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, co...",""],
["second_topic.htm","Introduction &#62; Second topic","Second topic Navigation: Introduction Second topic Enter topic text here. ",""],
["sub_chapter_2_1.htm","Chapter 2 &#62; Sub chapter 2.1","Sub chapter 2.1 Navigation: Chapter 2 Sub chapter 2.1 Enter topic text here. ",""],
["welcome_topic.htm","Introduction &#62; Welcome topic","Bienvenue sur CircLab ! Nous allons dans ce qui suit, vous présenter l&#39;interface ainsi que les différentes options que celle-ci offert, pour une f...",""]];
